<?php
// +----------------------------------------------------------------------
// | Legacy project 模块路由 — Phase 3 Batch 1–2
// +----------------------------------------------------------------------
use app\project\middleware\Auth;
use app\project\middleware\ProjectAuth;
use think\facade\Route;

$ns = 'app\\project\\controller\\';

$routes = [
    // Login（Gate A HV-A02 等）
    ['login/index', 'Login', 'index'],
    ['login/getCaptcha', 'Login', 'getCaptcha'],
    ['login/register', 'Login', 'register'],
    ['login/_bindMobile', 'Login', '_bindMobile'],
    ['login/_getMailCaptcha', 'Login', '_getMailCaptcha'],
    ['login/_bindMail', 'Login', '_bindMail'],
    ['login/_unbindDingtalk', 'Login', '_unbindDingtalk'],
    ['login/_checkBindMail', 'Login', '_checkBindMail'],
    ['login/_resetPasswordByMail', 'Login', '_resetPasswordByMail'],
    ['login/_checkLogin', 'Login', '_checkLogin'],
    ['login/_currentMember', 'Login', '_currentMember'],
    ['login/_out', 'Login', '_out'],
    // Index（菜单 / 组织 / 个人中心）
    ['index/index', 'Index', 'index'],
    ['index/_menus', 'Index', '_menus'],
    ['index/changeCurrentOrganization', 'Index', 'changeCurrentOrganization'],
    ['index/systemConfig', 'Index', 'systemConfig'],
    ['index/info', 'Index', 'info'],
    ['index/editPersonal', 'Index', 'editPersonal'],
    ['index/editPassword', 'Index', 'editPassword'],
    ['index/uploadImg', 'Index', 'uploadImg'],
    ['index/uploadAvatar', 'Index', 'uploadAvatar'],
    // Project
    ['project/index', 'Project', 'index'],
    ['project/analysis', 'Project', 'analysis'],
    ['project/selfList', 'Project', 'selfList'],
    ['project/save', 'Project', 'save'],
    ['project/read', 'Project', 'read'],
    ['project/edit', 'Project', 'edit'],
    ['project/getLogBySelfProject', 'Project', 'getLogBySelfProject'],
    ['project/_setDayilyProejctReport', 'Project', '_setDayilyProejctReport'],
    ['project/_getProjectReport', 'Project', '_getProjectReport'],
    ['project/_projectStats', 'Project', '_projectStats'],
    ['project/uploadCover', 'Project', 'uploadCover'],
    ['project/recycle', 'Project', 'recycle'],
    ['project/recovery', 'Project', 'recovery'],
    ['project/archive', 'Project', 'archive'],
    ['project/recoveryArchive', 'Project', 'recoveryArchive'],
    ['project/quit', 'Project', 'quit'],
    // ProjectMember
    ['projectMember/index', 'ProjectMember', 'index'],
    ['projectMember/_listForInvite', 'ProjectMember', '_listForInvite'],
    ['projectMember/searchInviteMember', 'ProjectMember', 'searchInviteMember'],
    ['projectMember/_joinByInviteLink', 'ProjectMember', '_joinByInviteLink'],
    ['projectMember/inviteMember', 'ProjectMember', 'inviteMember'],
    ['projectMember/removeMember', 'ProjectMember', 'removeMember'],
    // Task
    ['task/index', 'Task', 'index'],
    ['task/dateTotalForProject', 'Task', 'dateTotalForProject'],
    ['task/selfList', 'Task', 'selfList'],
    ['task/taskSources', 'Task', 'taskSources'],
    ['task/getListByTaskTag', 'Task', 'getListByTaskTag'],
    ['task/read', 'Task', 'read'],
    ['task/save', 'Task', 'save'],
    ['task/taskDone', 'Task', 'taskDone'],
    ['task/assignTask', 'Task', 'assignTask'],
    ['task/batchAssignTask', 'Task', 'batchAssignTask'],
    ['task/sort', 'Task', 'sort'],
    ['task/createComment', 'Task', 'createComment'],
    ['task/edit', 'Task', 'edit'],
    ['task/setPrivate', 'Task', 'setPrivate'],
    ['task/like', 'Task', 'like'],
    ['task/taskToTags', 'Task', 'taskToTags'],
    ['task/setTag', 'Task', 'setTag'],
    ['task/star', 'Task', 'star'],
    ['task/taskLog', 'Task', 'taskLog'],
    ['task/_taskWorkTimeList', 'Task', '_taskWorkTimeList'],
    ['task/saveTaskWorkTime', 'Task', 'saveTaskWorkTime'],
    ['task/editTaskWorkTime', 'Task', 'editTaskWorkTime'],
    ['task/delTaskWorkTime', 'Task', 'delTaskWorkTime'],
    ['task/_downloadTemplate', 'Task', '_downloadTemplate'],
    ['task/uploadFile', 'Task', 'uploadFile'],
    ['task/recycleBatch', 'Task', 'recycleBatch'],
    ['task/recycle', 'Task', 'recycle'],
    ['task/recovery', 'Task', 'recovery'],
    ['task/delete', 'Task', 'delete'],
    // TaskStages
    ['taskStages/index', 'TaskStages', 'index'],
    ['taskStages/_getAll', 'TaskStages', '_getAll'],
    ['taskStages/tasks', 'TaskStages', 'tasks'],
    ['taskStages/taskTree', 'TaskStages', 'taskTree'],
    ['taskStages/sort', 'TaskStages', 'sort'],
    ['taskStages/save', 'TaskStages', 'save'],
    ['taskStages/edit', 'TaskStages', 'edit'],
    ['taskStages/delete', 'TaskStages', 'delete'],
    // TaskMember
    ['taskMember/index', 'TaskMember', 'index'],
    ['taskMember/searchInviteMember', 'TaskMember', 'searchInviteMember'],
    ['taskMember/inviteMember', 'TaskMember', 'inviteMember'],
    ['taskMember/inviteMemberBatch', 'TaskMember', 'inviteMemberBatch'],
    // File
    ['file/index', 'File', 'index'],
    ['file/read', 'File', 'read'],
    ['file/uploadFiles', 'File', 'uploadFiles'],
    ['file/edit', 'File', 'edit'],
    ['file/recycle', 'File', 'recycle'],
    ['file/recovery', 'File', 'recovery'],
    ['file/delete', 'File', 'delete'],
    // Notify
    ['notify/index', 'Notify', 'index'],
    ['notify/noReads', 'Notify', 'noReads'],
    ['notify/setReadied', 'Notify', 'setReadied'],
    ['notify/_clearAll', 'Notify', '_clearAll'],
    ['notify/batchDel', 'Notify', 'batchDel'],
    ['notify/read', 'Notify', 'read'],
    ['notify/delete', 'Notify', 'delete'],
    // Organization
    ['organization/_getOrgList', 'Organization', '_getOrgList'],
    ['organization/index', 'Organization', 'index'],
    ['organization/save', 'Organization', 'save'],
    ['organization/read', 'Organization', 'read'],
    ['organization/edit', 'Organization', 'edit'],
    ['organization/delete', 'Organization', 'delete'],
    ['organization/_quitOrganization', 'Organization', '_quitOrganization'],
    // Account
    ['account/index', 'Account', 'index'],
    ['account/_allList', 'Account', '_allList'],
    ['account/read', 'Account', 'read'],
    ['account/auth', 'Account', 'auth'],
    ['account/_joinByInviteLink', 'Account', '_joinByInviteLink'],
    ['account/_syncDetail', 'Account', '_syncDetail'],
    ['account/add', 'Account', 'add'],
    ['account/edit', 'Account', 'edit'],
    ['account/del', 'Account', 'del'],
    ['account/forbid', 'Account', 'forbid'],
    ['account/resume', 'Account', 'resume'],
    // Department
    ['department/index', 'Department', 'index'],
    ['department/read', 'Department', 'read'],
    ['department/save', 'Department', 'save'],
    ['department/edit', 'Department', 'edit'],
    ['department/delete', 'Department', 'delete'],
    // DepartmentMember
    ['departmentMember/index', 'DepartmentMember', 'index'],
    ['departmentMember/detail', 'DepartmentMember', 'detail'],
    ['departmentMember/searchInviteMember', 'DepartmentMember', 'searchInviteMember'],
    ['departmentMember/inviteMember', 'DepartmentMember', 'inviteMember'],
    ['departmentMember/removeMember', 'DepartmentMember', 'removeMember'],
    ['departmentMember/_downloadTemplate', 'DepartmentMember', '_downloadTemplate'],
    ['departmentMember/uploadFile', 'DepartmentMember', 'uploadFile'],
    // TaskTag
    ['taskTag/index', 'TaskTag', 'index'],
    ['taskTag/save', 'TaskTag', 'save'],
    ['taskTag/edit', 'TaskTag', 'edit'],
    ['taskTag/delete', 'TaskTag', 'delete'],
    // ProjectCollect
    ['projectCollect/collect', 'ProjectCollect', 'collect'],
    // Auth
    ['auth/index', 'Auth', 'index'],
    ['auth/apply', 'Auth', 'apply'],
    ['auth/add', 'Auth', 'add'],
    ['auth/edit', 'Auth', 'edit'],
    ['auth/del', 'Auth', 'del'],
    ['auth/forbid', 'Auth', 'forbid'],
    ['auth/resume', 'Auth', 'resume'],
    ['auth/setDefault', 'Auth', 'setDefault'],
    // Menu
    ['menu/menu', 'Menu', 'menu'],
    ['menu/menuAdd', 'Menu', 'menuAdd'],
    ['menu/menuEdit', 'Menu', 'menuEdit'],
    ['menu/menuForbid', 'Menu', 'menuForbid'],
    ['menu/menuResume', 'Menu', 'menuResume'],
    ['menu/menuDel', 'Menu', 'menuDel'],
    // Node
    ['node/index', 'Node', 'index'],
    ['node/allList', 'Node', 'allList'],
    ['node/save', 'Node', 'save'],
    ['node/clear', 'Node', 'clear'],
    // Events
    ['events/index', 'Events', 'index'],
    ['events/myList', 'Events', 'myList'],
    ['events/confirmList', 'Events', 'confirmList'],
    ['events/save', 'Events', 'save'],
    ['events/edit', 'Events', 'edit'],
    ['events/read', 'Events', 'read'],
    ['events/confirmJoin', 'Events', 'confirmJoin'],
    ['events/removeMember', 'Events', 'removeMember'],
    ['events/inviteMember', 'Events', 'inviteMember'],
    ['events/getEventsListByCalendar', 'Events', 'getEventsListByCalendar'],
    ['events/_getEventsLog', 'Events', '_getEventsLog'],
    ['events/delete', 'Events', 'delete'],
    // InviteLink
    ['inviteLink/save', 'InviteLink', 'save'],
    ['inviteLink/_read', 'InviteLink', '_read'],
];

Route::group('project', function () use ($ns, $routes) {
    foreach ($routes as [$path, $controller, $action]) {
        Route::rule($path, $ns . $controller . '@' . $action)
            ->method('GET|POST|PUT|DELETE|PATCH');
    }
})->middleware([Auth::class, ProjectAuth::class]);
